### ISSUE TITLE
Does not work with Babel 6

### ISSUE THREAD

**Issue by andrewcoelho** [rackt/example-react-router-server-rendering-lazy-routes#1]
I tried integrating the techniques here with my app that's using Babel 6. I kept getting 404's on child routes and I couldn't understand why. Finally, I updated all the dependencies on my clone of this repo to the latest versions to see if the problem was with my dependencies, and sure enough, it's giving me the same issues.

Here's what I updated the dependencies to:

```
"dependencies": {
    "babel-core": "^6.3.26",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "history": "^1.17.0",
    "react": "^0.14.3",
    "react-dom": "^0.14.3",
    "react-router": "^1.0.3",
    "webpack": "^1.12.9"
  }
```

and I have a .babelrc like this 

```
{
  "presets": ["react", "es2015"]
}
```

Upon running `npm start`, everything is OK, console output is good. I navigate to localhost:5000, and the index page shows up. But if you click on "About", nothing happens, and if you visit localhost:5000/about directly you get a "Not Found" from the server.

I'm not 100% sure this is a Babel 6 issue or if potentially something else changed in the other libraries that's causing this.

Any idea what's going on?

**Comment by apalm** [comment]
With Babel 6, modules with a default export no longer put it on `module.exports`.

You'll need to require like this:

``` js
require('./MyRoute').default
```

Alternatively, you can export your route using `module.exports`.

More info here: http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default

**Comment by andrewcoelho** [comment]
That did it. Thanks!
