### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by Michal-Miky-Jankovsky** [rackt/example-react-router-server-rendering-lazy-routes#2]
Hi,

I did steps by README.md (attached files), but start failed.

[command-line.txt](https://github.com/rackt/example-react-router-server-rendering-lazy-routes/files/77736/command-line.txt)
[npm-debug.txt](https://github.com/rackt/example-react-router-server-rendering-lazy-routes/files/77737/npm-debug.txt)

Thanks

Miky

**Comment by pgib** [comment]
![windows](http://i.giphy.com/DO9WQFLaAEnM4.gif)

```
> NODE_ENV=production webpack --progress && babel-node modules/server.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
```

It's complaining about how this environment variable is set here. It looks like you're using Windows, so you'll need to adapt any examples to the Windows way of doing things. You'll probably have a much simpler time to install VirtualBox (or your favourite VM)  and run some Linux or BSD distribution. 99% of the examples and documentation for node.js type stuff is going to assume a POSIX shell. Cygwin may be something to look at, but I'd recommend you be like water and follow the path of least resistance. 😉

**Comment by Michal-Miky-Jankovsky** [comment]
Hi Patric,

thanks for quick answer. You're right windows script has another syntax.

I changed package.json in the root of project.
- Now it works with Windows:

"scripts": {
    "start": "**SET** NODE_ENV=production **&** webpack --progress **&** babel-node modules/server.js"
},
- Instead of Linux version:

"scripts": {
    "start": "NODE_ENV=production webpack --progress && babel-node modules/server.js"
},

Miky
