### ISSUE TITLE
Proper way to import assets

### ISSUE THREAD

**Issue by kennetpostigo** [rackt/example-react-router-server-rendering-lazy-routes#9]
Hello,

I'm currently using this project as the basis for a personal project. I've got everything working well.
My question is how to properly process styles using this architecture. I'm attempting to process the files using scss with `styles-loader`, `sass-loader`, `node-sass`, and `css-loader`. When doing this it causes the component to load and then after 2 seconds the styles finally load. I then tried to process the scss outside of webpack but it changes the content type to from `css` to `plain-text`.

How do you go about processing your styles with an architecture like this?

**Comment by ryanflorence** [comment]
use https://github.com/ryanflorence/react-project, it does everything you need.

**Comment by kennetpostigo** [comment]
Okay thank you @ryanflorence
